baseURL: 'https://kalinlai-void.github.io/ACGN/'
languageCode: zh-tw
defaultContentLanguage: zh-tw
title: Kalin 風凜魂太の宅領域

theme: PaperMod
disqusShortname: kalin-acgn

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: G-4BT4PPKP52

minify:
    disableXML: true
    # minifyOutput: true

menu:
  main:
    - name: 分類
      url: categories/
      weight: 1
    - name: 標籤
      url: tags/
      weight: 2
    - name: 歷史文章
      url: archive/
      weight: 3
    - name: 搜尋
      url: search/
      weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    likerID: kalinlai
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    #description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Kalin 風凜魂太
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    TocOpen: true
    ShowPostNavLinks: true
    comments: true

    #profileMode:
    #    enabled: false
    #    title: PaperMod
    #    imageUrl: "#"
    #    imageTitle: my image
    #    # imageWidth: 120
    #    # imageHeight: 120
    #    buttons:
    #        - name: Archives
    #          url: archives
    #        - name: Tags
    #          url: tags

    homeInfoParams:
        Title: "Kalin 風凜魂太の宅領域"
        Content: >
            就是個喜歡分享個人看法（以ACGN為主）的宅宅，同時也是名往「遊戲產業」邁進的年輕人。<br>
            - 這邊僅會分享ACGN相關看法，如心得之類的。<br>
            - 若對技術文章有興趣，可以看看我的[主Blog](https://kalinlai-void.github.io/)。<br>
            - 歡迎各位在文章下方跟我討論xD，有空我就會回！
    socialIcons:
        - name: Facebook
          url: "https://www.facebook.com/animeKarinKonta"
        - name: RsS
          url: "index.xml"

    label:
        text: "Kalin 風凜魂太の宅領域"
        icon: icon/favicon.ico
        iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    adsense:
      client: "ca-pub-9358449882725994"
      inArticleSlot: "9718442885"

    assets:
        favicon: icon/favicon.ico
        favicon16x16: icon/favicon-16x16.png
        favicon32x32: icon/favicon-32x32.png
        apple_touch_icon: icon/apple-touch-icon.png

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai